/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Make all properties in T optional
 * @export
 * @interface PartialUserInterface_
 */
export interface PartialUserInterface_ {
    /**
     * 
     * @type {string}
     * @memberof PartialUserInterface_
     */
    userId?: any;
    /**
     * 
     * @type {string}
     * @memberof PartialUserInterface_
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof PartialUserInterface_
     */
    password?: any;
    /**
     * 
     * @type {Array&lt;PartialUserInterfaceProjectsJoined&gt;}
     * @memberof PartialUserInterface_
     */
    projectsJoined?: any;
    /**
     * 
     * @type {Array&lt;PartialUserInterfaceTransactions&gt;}
     * @memberof PartialUserInterface_
     */
    transactions?: any;
}
