/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectInterface
 */
export interface ProjectInterface {
    /**
     * 
     * @type {string}
     * @memberof ProjectInterface
     */
    projectId: any;
    /**
     * 
     * @type {string}
     * @memberof ProjectInterface
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof ProjectInterface
     */
    description: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ProjectInterface
     */
    usersJoined: any;
    /**
     * 
     * @type {string}
     * @memberof ProjectInterface
     */
    admin: any;
    /**
     * 
     * @type {{ [key, string]: ProjectInterfaceResources;}}
     * @memberof ProjectInterface
     */
    resources: any;
    /**
     * 
     * @type {number}
     * @memberof ProjectInterface
     */
    currentResources: any;
    /**
     * 
     * @type {Array&lt;ProjectInterfaceTransactions&gt;}
     * @memberof ProjectInterface
     */
    transactions: any;
}
