/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ResetBody
 */
export interface ResetBody {
    /**
     * 
     * @type {string}
     * @memberof ResetBody
     */
    repassword: any;
    /**
     * 
     * @type {string}
     * @memberof ResetBody
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof ResetBody
     */
    username: any;
}
