/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AnyOfinlineResponse2001 model module.
 * @module model/AnyOfinlineResponse2001
 * @version 1.0.0
 */
export class AnyOfinlineResponse2001 {
  /**
   * Constructs a new <code>AnyOfinlineResponse2001</code>.
   * @alias module:model/AnyOfinlineResponse2001
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnyOfinlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnyOfinlineResponse2001} obj Optional instance to populate.
   * @return {module:model/AnyOfinlineResponse2001} The populated <code>AnyOfinlineResponse2001</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnyOfinlineResponse2001();
    }
    return obj;
  }
}
