/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CheckinoutCheckinBody model module.
 * @module model/CheckinoutCheckinBody
 * @version 1.0.0
 */
export class CheckinoutCheckinBody {
  /**
   * Constructs a new <code>CheckinoutCheckinBody</code>.
   * @alias module:model/CheckinoutCheckinBody
   * @class
   * @param projectId {String} 
   * @param userId {String} 
   * @param amount {Number} 
   * @param hwSetId {String} 
   */
  constructor(projectId, userId, amount, hwSetId) {
    this.projectId = projectId;
    this.userId = userId;
    this.amount = amount;
    this.hwSetId = hwSetId;
  }

  /**
   * Constructs a <code>CheckinoutCheckinBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckinoutCheckinBody} obj Optional instance to populate.
   * @return {module:model/CheckinoutCheckinBody} The populated <code>CheckinoutCheckinBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckinoutCheckinBody();
      if (data.hasOwnProperty('projectId'))
        obj.projectId = ApiClient.convertToType(data['projectId'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('hwSetId'))
        obj.hwSetId = ApiClient.convertToType(data['hwSetId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} projectId
 */
CheckinoutCheckinBody.prototype.projectId = undefined;

/**
 * @member {String} userId
 */
CheckinoutCheckinBody.prototype.userId = undefined;

/**
 * @member {Number} amount
 */
CheckinoutCheckinBody.prototype.amount = undefined;

/**
 * @member {String} hwSetId
 */
CheckinoutCheckinBody.prototype.hwSetId = undefined;

