/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProjectInterface} from './ProjectInterface';
import {ProjectInterfaceResources} from './ProjectInterfaceResources';
import {ProjectInterfaceTransactions} from './ProjectInterfaceTransactions';

/**
 * The InlineResponse2003 model module.
 * @module model/InlineResponse2003
 * @version 1.0.0
 */
export class InlineResponse2003 extends ProjectInterface {
  /**
   * Constructs a new <code>InlineResponse2003</code>.
   * @alias module:model/InlineResponse2003
   * @class
   * @extends module:model/ProjectInterface
   * @param projectId {} 
   * @param name {} 
   * @param description {} 
   * @param usersJoined {} 
   * @param admin {} 
   * @param resources {} 
   * @param currentResources {} 
   * @param transactions {} 
   */
  constructor(projectId, name, description, usersJoined, admin, resources, currentResources, transactions) {
    super(projectId, name, description, usersJoined, admin, resources, currentResources, transactions);
  }

  /**
   * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2003();
      ProjectInterface.constructFromObject(data, obj);
    }
    return obj;
  }
}
