/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PartialUserInterfaceProjectsJoined} from './PartialUserInterfaceProjectsJoined';
import {PartialUserInterfaceTransactions} from './PartialUserInterfaceTransactions';

/**
 * The PartialUserInterface_ model module.
 * @module model/PartialUserInterface_
 * @version 1.0.0
 */
export class PartialUserInterface_ {
  /**
   * Constructs a new <code>PartialUserInterface_</code>.
   * Make all properties in T optional
   * @alias module:model/PartialUserInterface_
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PartialUserInterface_</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartialUserInterface_} obj Optional instance to populate.
   * @return {module:model/PartialUserInterface_} The populated <code>PartialUserInterface_</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PartialUserInterface_();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('projectsJoined'))
        obj.projectsJoined = ApiClient.convertToType(data['projectsJoined'], [PartialUserInterfaceProjectsJoined]);
      if (data.hasOwnProperty('transactions'))
        obj.transactions = ApiClient.convertToType(data['transactions'], [PartialUserInterfaceTransactions]);
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
PartialUserInterface_.prototype.userId = undefined;

/**
 * @member {String} username
 */
PartialUserInterface_.prototype.username = undefined;

/**
 * @member {String} password
 */
PartialUserInterface_.prototype.password = undefined;

/**
 * @member {Array.<module:model/PartialUserInterfaceProjectsJoined>} projectsJoined
 */
PartialUserInterface_.prototype.projectsJoined = undefined;

/**
 * @member {Array.<module:model/PartialUserInterfaceTransactions>} transactions
 */
PartialUserInterface_.prototype.transactions = undefined;

