/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PartialUserInterfaceTransactions model module.
 * @module model/PartialUserInterfaceTransactions
 * @version 1.0.0
 */
export class PartialUserInterfaceTransactions {
  /**
   * Constructs a new <code>PartialUserInterfaceTransactions</code>.
   * @alias module:model/PartialUserInterfaceTransactions
   * @class
   * @param projectId {String} 
   * @param hwSetName {String} 
   * @param hwSetId {String} 
   * @param amount {Number} 
   * @param action {module:model/PartialUserInterfaceTransactions.ActionEnum} 
   */
  constructor(projectId, hwSetName, hwSetId, amount, action) {
    this.projectId = projectId;
    this.hwSetName = hwSetName;
    this.hwSetId = hwSetId;
    this.amount = amount;
    this.action = action;
  }

  /**
   * Constructs a <code>PartialUserInterfaceTransactions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartialUserInterfaceTransactions} obj Optional instance to populate.
   * @return {module:model/PartialUserInterfaceTransactions} The populated <code>PartialUserInterfaceTransactions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PartialUserInterfaceTransactions();
      if (data.hasOwnProperty('projectId'))
        obj.projectId = ApiClient.convertToType(data['projectId'], 'String');
      if (data.hasOwnProperty('hwSetName'))
        obj.hwSetName = ApiClient.convertToType(data['hwSetName'], 'String');
      if (data.hasOwnProperty('hwSetId'))
        obj.hwSetId = ApiClient.convertToType(data['hwSetId'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} projectId
 */
PartialUserInterfaceTransactions.prototype.projectId = undefined;

/**
 * @member {String} hwSetName
 */
PartialUserInterfaceTransactions.prototype.hwSetName = undefined;

/**
 * @member {String} hwSetId
 */
PartialUserInterfaceTransactions.prototype.hwSetId = undefined;

/**
 * @member {Number} amount
 */
PartialUserInterfaceTransactions.prototype.amount = undefined;

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
PartialUserInterfaceTransactions.ActionEnum = {
  /**
   * value: "checkin"
   * @const
   */
  checkin: "checkin",

  /**
   * value: "checkout"
   * @const
   */
  checkout: "checkout"
};
/**
 * @member {module:model/PartialUserInterfaceTransactions.ActionEnum} action
 */
PartialUserInterfaceTransactions.prototype.action = undefined;

