/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PartialUserInterfaceProjectsJoined model module.
 * @module model/PartialUserInterfaceProjectsJoined
 * @version 1.0.0
 */
export class PartialUserInterfaceProjectsJoined {
  /**
   * Constructs a new <code>PartialUserInterfaceProjectsJoined</code>.
   * @alias module:model/PartialUserInterfaceProjectsJoined
   * @class
   * @param role {module:model/PartialUserInterfaceProjectsJoined.RoleEnum} 
   * @param projectId {String} 
   */
  constructor(role, projectId) {
    this.role = role;
    this.projectId = projectId;
  }

  /**
   * Constructs a <code>PartialUserInterfaceProjectsJoined</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartialUserInterfaceProjectsJoined} obj Optional instance to populate.
   * @return {module:model/PartialUserInterfaceProjectsJoined} The populated <code>PartialUserInterfaceProjectsJoined</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PartialUserInterfaceProjectsJoined();
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('projectId'))
        obj.projectId = ApiClient.convertToType(data['projectId'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
PartialUserInterfaceProjectsJoined.RoleEnum = {
  /**
   * value: "admin"
   * @const
   */
  admin: "admin",

  /**
   * value: "member"
   * @const
   */
  member: "member"
};
/**
 * @member {module:model/PartialUserInterfaceProjectsJoined.RoleEnum} role
 */
PartialUserInterfaceProjectsJoined.prototype.role = undefined;

/**
 * @member {String} projectId
 */
PartialUserInterfaceProjectsJoined.prototype.projectId = undefined;

