/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProjectAddUserBody model module.
 * @module model/ProjectAddUserBody
 * @version 1.0.0
 */
export class ProjectAddUserBody {
  /**
   * Constructs a new <code>ProjectAddUserBody</code>.
   * @alias module:model/ProjectAddUserBody
   * @class
   * @param projectId {String} 
   * @param userId {String} 
   */
  constructor(projectId, userId) {
    this.projectId = projectId;
    this.userId = userId;
  }

  /**
   * Constructs a <code>ProjectAddUserBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectAddUserBody} obj Optional instance to populate.
   * @return {module:model/ProjectAddUserBody} The populated <code>ProjectAddUserBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectAddUserBody();
      if (data.hasOwnProperty('projectId'))
        obj.projectId = ApiClient.convertToType(data['projectId'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} projectId
 */
ProjectAddUserBody.prototype.projectId = undefined;

/**
 * @member {String} userId
 */
ProjectAddUserBody.prototype.userId = undefined;

