/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProjectCreateBody model module.
 * @module model/ProjectCreateBody
 * @version 1.0.0
 */
export class ProjectCreateBody {
  /**
   * Constructs a new <code>ProjectCreateBody</code>.
   * @alias module:model/ProjectCreateBody
   * @class
   * @param userId {String} 
   * @param description {String} 
   * @param name {String} 
   */
  constructor(userId, description, name) {
    this.userId = userId;
    this.description = description;
    this.name = name;
  }

  /**
   * Constructs a <code>ProjectCreateBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectCreateBody} obj Optional instance to populate.
   * @return {module:model/ProjectCreateBody} The populated <code>ProjectCreateBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectCreateBody();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
ProjectCreateBody.prototype.userId = undefined;

/**
 * @member {String} description
 */
ProjectCreateBody.prototype.description = undefined;

/**
 * @member {String} name
 */
ProjectCreateBody.prototype.name = undefined;

