/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProjectInterfaceUsersCheckedOut model module.
 * @module model/ProjectInterfaceUsersCheckedOut
 * @version 1.0.0
 */
export class ProjectInterfaceUsersCheckedOut {
  /**
   * Constructs a new <code>ProjectInterfaceUsersCheckedOut</code>.
   * @alias module:model/ProjectInterfaceUsersCheckedOut
   * @class
   * @param checkedOutBy {String} 
   * @param amount {Number} 
   */
  constructor(checkedOutBy, amount) {
    this.checkedOutBy = checkedOutBy;
    this.amount = amount;
  }

  /**
   * Constructs a <code>ProjectInterfaceUsersCheckedOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectInterfaceUsersCheckedOut} obj Optional instance to populate.
   * @return {module:model/ProjectInterfaceUsersCheckedOut} The populated <code>ProjectInterfaceUsersCheckedOut</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectInterfaceUsersCheckedOut();
      if (data.hasOwnProperty('checkedOutBy'))
        obj.checkedOutBy = ApiClient.convertToType(data['checkedOutBy'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} checkedOutBy
 */
ProjectInterfaceUsersCheckedOut.prototype.checkedOutBy = undefined;

/**
 * @member {Number} amount
 */
ProjectInterfaceUsersCheckedOut.prototype.amount = undefined;

