/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProjectInterfaceTransactions model module.
 * @module model/ProjectInterfaceTransactions
 * @version 1.0.0
 */
export class ProjectInterfaceTransactions {
  /**
   * Constructs a new <code>ProjectInterfaceTransactions</code>.
   * @alias module:model/ProjectInterfaceTransactions
   * @class
   * @param userId {String} 
   * @param hwSetName {String} 
   * @param hwSetId {String} 
   * @param amount {Number} 
   * @param action {module:model/ProjectInterfaceTransactions.ActionEnum} 
   */
  constructor(userId, hwSetName, hwSetId, amount, action) {
    this.userId = userId;
    this.hwSetName = hwSetName;
    this.hwSetId = hwSetId;
    this.amount = amount;
    this.action = action;
  }

  /**
   * Constructs a <code>ProjectInterfaceTransactions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectInterfaceTransactions} obj Optional instance to populate.
   * @return {module:model/ProjectInterfaceTransactions} The populated <code>ProjectInterfaceTransactions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectInterfaceTransactions();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('hwSetName'))
        obj.hwSetName = ApiClient.convertToType(data['hwSetName'], 'String');
      if (data.hasOwnProperty('hwSetId'))
        obj.hwSetId = ApiClient.convertToType(data['hwSetId'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
ProjectInterfaceTransactions.prototype.userId = undefined;

/**
 * @member {String} hwSetName
 */
ProjectInterfaceTransactions.prototype.hwSetName = undefined;

/**
 * @member {String} hwSetId
 */
ProjectInterfaceTransactions.prototype.hwSetId = undefined;

/**
 * @member {Number} amount
 */
ProjectInterfaceTransactions.prototype.amount = undefined;

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
ProjectInterfaceTransactions.ActionEnum = {
  /**
   * value: "checkin"
   * @const
   */
  checkin: "checkin",

  /**
   * value: "checkout"
   * @const
   */
  checkout: "checkout"
};
/**
 * @member {module:model/ProjectInterfaceTransactions.ActionEnum} action
 */
ProjectInterfaceTransactions.prototype.action = undefined;

