/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProjectInterfaceUsersCheckedOut} from './ProjectInterfaceUsersCheckedOut';

/**
 * The ProjectInterfaceResources model module.
 * @module model/ProjectInterfaceResources
 * @version 1.0.0
 */
export class ProjectInterfaceResources {
  /**
   * Constructs a new <code>ProjectInterfaceResources</code>.
   * @alias module:model/ProjectInterfaceResources
   * @class
   * @param usersCheckedOut {Array.<module:model/ProjectInterfaceUsersCheckedOut>} 
   * @param totalResources {Number} 
   */
  constructor(usersCheckedOut, totalResources) {
    this.usersCheckedOut = usersCheckedOut;
    this.totalResources = totalResources;
  }

  /**
   * Constructs a <code>ProjectInterfaceResources</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectInterfaceResources} obj Optional instance to populate.
   * @return {module:model/ProjectInterfaceResources} The populated <code>ProjectInterfaceResources</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectInterfaceResources();
      if (data.hasOwnProperty('usersCheckedOut'))
        obj.usersCheckedOut = ApiClient.convertToType(data['usersCheckedOut'], [ProjectInterfaceUsersCheckedOut]);
      if (data.hasOwnProperty('totalResources'))
        obj.totalResources = ApiClient.convertToType(data['totalResources'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ProjectInterfaceUsersCheckedOut>} usersCheckedOut
 */
ProjectInterfaceResources.prototype.usersCheckedOut = undefined;

/**
 * @member {Number} totalResources
 */
ProjectInterfaceResources.prototype.totalResources = undefined;

