/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResetBody model module.
 * @module model/ResetBody
 * @version 1.0.0
 */
export class ResetBody {
  /**
   * Constructs a new <code>ResetBody</code>.
   * @alias module:model/ResetBody
   * @class
   * @param repassword {String} 
   * @param password {String} 
   * @param username {String} 
   */
  constructor(repassword, password, username) {
    this.repassword = repassword;
    this.password = password;
    this.username = username;
  }

  /**
   * Constructs a <code>ResetBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResetBody} obj Optional instance to populate.
   * @return {module:model/ResetBody} The populated <code>ResetBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResetBody();
      if (data.hasOwnProperty('repassword'))
        obj.repassword = ApiClient.convertToType(data['repassword'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} repassword
 */
ResetBody.prototype.repassword = undefined;

/**
 * @member {String} password
 */
ResetBody.prototype.password = undefined;

/**
 * @member {String} username
 */
ResetBody.prototype.username = undefined;

