/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ResourceInterfaceTransactions} from './ResourceInterfaceTransactions';

/**
 * The ResourceInterface model module.
 * @module model/ResourceInterface
 * @version 1.0.0
 */
export class ResourceInterface {
  /**
   * Constructs a new <code>ResourceInterface</code>.
   * @alias module:model/ResourceInterface
   * @class
   * @param hwSetId {String} 
   * @param hwSetName {String} 
   * @param capacity {Number} 
   * @param availablity {Number} 
   * @param transactions {Array.<module:model/ResourceInterfaceTransactions>} 
   */
  constructor(hwSetId, hwSetName, capacity, availablity, transactions) {
    this.hwSetId = hwSetId;
    this.hwSetName = hwSetName;
    this.capacity = capacity;
    this.availablity = availablity;
    this.transactions = transactions;
  }

  /**
   * Constructs a <code>ResourceInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResourceInterface} obj Optional instance to populate.
   * @return {module:model/ResourceInterface} The populated <code>ResourceInterface</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResourceInterface();
      if (data.hasOwnProperty('hwSetId'))
        obj.hwSetId = ApiClient.convertToType(data['hwSetId'], 'String');
      if (data.hasOwnProperty('hwSetName'))
        obj.hwSetName = ApiClient.convertToType(data['hwSetName'], 'String');
      if (data.hasOwnProperty('capacity'))
        obj.capacity = ApiClient.convertToType(data['capacity'], 'Number');
      if (data.hasOwnProperty('availablity'))
        obj.availablity = ApiClient.convertToType(data['availablity'], 'Number');
      if (data.hasOwnProperty('transactions'))
        obj.transactions = ApiClient.convertToType(data['transactions'], [ResourceInterfaceTransactions]);
    }
    return obj;
  }
}

/**
 * @member {String} hwSetId
 */
ResourceInterface.prototype.hwSetId = undefined;

/**
 * @member {String} hwSetName
 */
ResourceInterface.prototype.hwSetName = undefined;

/**
 * @member {Number} capacity
 */
ResourceInterface.prototype.capacity = undefined;

/**
 * @member {Number} availablity
 */
ResourceInterface.prototype.availablity = undefined;

/**
 * @member {Array.<module:model/ResourceInterfaceTransactions>} transactions
 */
ResourceInterface.prototype.transactions = undefined;

