/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResourceInterfaceTransactions model module.
 * @module model/ResourceInterfaceTransactions
 * @version 1.0.0
 */
export class ResourceInterfaceTransactions {
  /**
   * Constructs a new <code>ResourceInterfaceTransactions</code>.
   * @alias module:model/ResourceInterfaceTransactions
   * @class
   * @param projectId {String} 
   * @param userId {String} 
   * @param amount {Number} 
   * @param action {module:model/ResourceInterfaceTransactions.ActionEnum} 
   */
  constructor(projectId, userId, amount, action) {
    this.projectId = projectId;
    this.userId = userId;
    this.amount = amount;
    this.action = action;
  }

  /**
   * Constructs a <code>ResourceInterfaceTransactions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResourceInterfaceTransactions} obj Optional instance to populate.
   * @return {module:model/ResourceInterfaceTransactions} The populated <code>ResourceInterfaceTransactions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResourceInterfaceTransactions();
      if (data.hasOwnProperty('projectId'))
        obj.projectId = ApiClient.convertToType(data['projectId'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} projectId
 */
ResourceInterfaceTransactions.prototype.projectId = undefined;

/**
 * @member {String} userId
 */
ResourceInterfaceTransactions.prototype.userId = undefined;

/**
 * @member {Number} amount
 */
ResourceInterfaceTransactions.prototype.amount = undefined;

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
ResourceInterfaceTransactions.ActionEnum = {
  /**
   * value: "checkin"
   * @const
   */
  checkin: "checkin",

  /**
   * value: "checkout"
   * @const
   */
  checkout: "checkout"
};
/**
 * @member {module:model/ResourceInterfaceTransactions.ActionEnum} action
 */
ResourceInterfaceTransactions.prototype.action = undefined;

