/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CheckinoutCheckoutBody
 */
export interface CheckinoutCheckoutBody {
    /**
     * 
     * @type {string}
     * @memberof CheckinoutCheckoutBody
     */
    projectId: any;
    /**
     * 
     * @type {string}
     * @memberof CheckinoutCheckoutBody
     */
    userId: any;
    /**
     * 
     * @type {number}
     * @memberof CheckinoutCheckoutBody
     */
    amount: any;
    /**
     * 
     * @type {string}
     * @memberof CheckinoutCheckoutBody
     */
    hwSetId: any;
}
