/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProjectInterface } from ".";

/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 extends ProjectInterface {
}
