/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PartialUserInterfaceProjectsJoined
 */
export interface PartialUserInterfaceProjectsJoined {
    /**
     * 
     * @type {string}
     * @memberof PartialUserInterfaceProjectsJoined
     */
    role: PartialUserInterfaceProjectsJoinedRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof PartialUserInterfaceProjectsJoined
     */
    projectId: any;
}

/**
    * @export
    * @enum {string}
    */
export enum PartialUserInterfaceProjectsJoinedRoleEnum {
    Admin = 'admin',
    Member = 'member'
}

