/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectCreateBody
 */
export interface ProjectCreateBody {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateBody
     */
    userId: any;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateBody
     */
    description: any;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateBody
     */
    name: any;
}
