/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cirquick);
  }
}(this, function(expect, Cirquick) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2005', function() {
      beforeEach(function() {
        instance = new Cirquick.InlineResponse2005();
      });

      it('should create an instance of InlineResponse2005', function() {
        // TODO: update the code to test InlineResponse2005
        expect(instance).to.be.a(Cirquick.InlineResponse2005);
      });

      it('should have the property echoed (base name: "echoed")', function() {
        // TODO: update the code to test the property echoed
        expect(instance).to.have.property('echoed');
        // expect(instance.echoed).to.be(expectedValueLiteral);
      });

    });
  });

}));
