/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cirquick);
  }
}(this, function(expect, Cirquick) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PartialUserInterfaceProjectsJoined', function() {
      beforeEach(function() {
        instance = new Cirquick.PartialUserInterfaceProjectsJoined();
      });

      it('should create an instance of PartialUserInterfaceProjectsJoined', function() {
        // TODO: update the code to test PartialUserInterfaceProjectsJoined
        expect(instance).to.be.a(Cirquick.PartialUserInterfaceProjectsJoined);
      });

      it('should have the property role (base name: "role")', function() {
        // TODO: update the code to test the property role
        expect(instance).to.have.property('role');
        // expect(instance.role).to.be(expectedValueLiteral);
      });

      it('should have the property projectId (base name: "projectId")', function() {
        // TODO: update the code to test the property projectId
        expect(instance).to.have.property('projectId');
        // expect(instance.projectId).to.be(expectedValueLiteral);
      });

    });
  });

}));
