/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cirquick);
  }
}(this, function(expect, Cirquick) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ResetBody', function() {
      beforeEach(function() {
        instance = new Cirquick.ResetBody();
      });

      it('should create an instance of ResetBody', function() {
        // TODO: update the code to test ResetBody
        expect(instance).to.be.a(Cirquick.ResetBody);
      });

      it('should have the property repassword (base name: "repassword")', function() {
        // TODO: update the code to test the property repassword
        expect(instance).to.have.property('repassword');
        // expect(instance.repassword).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property username (base name: "username")', function() {
        // TODO: update the code to test the property username
        expect(instance).to.have.property('username');
        // expect(instance.username).to.be(expectedValueLiteral);
      });

    });
  });

}));
