/*
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cirquick);
  }
}(this, function(expect, Cirquick) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ResourceInterface', function() {
      beforeEach(function() {
        instance = new Cirquick.ResourceInterface();
      });

      it('should create an instance of ResourceInterface', function() {
        // TODO: update the code to test ResourceInterface
        expect(instance).to.be.a(Cirquick.ResourceInterface);
      });

      it('should have the property hwSetId (base name: "hwSetId")', function() {
        // TODO: update the code to test the property hwSetId
        expect(instance).to.have.property('hwSetId');
        // expect(instance.hwSetId).to.be(expectedValueLiteral);
      });

      it('should have the property hwSetName (base name: "hwSetName")', function() {
        // TODO: update the code to test the property hwSetName
        expect(instance).to.have.property('hwSetName');
        // expect(instance.hwSetName).to.be(expectedValueLiteral);
      });

      it('should have the property capacity (base name: "capacity")', function() {
        // TODO: update the code to test the property capacity
        expect(instance).to.have.property('capacity');
        // expect(instance.capacity).to.be(expectedValueLiteral);
      });

      it('should have the property availablity (base name: "availablity")', function() {
        // TODO: update the code to test the property availablity
        expect(instance).to.have.property('availablity');
        // expect(instance.availablity).to.be(expectedValueLiteral);
      });

      it('should have the property transactions (base name: "transactions")', function() {
        // TODO: update the code to test the property transactions
        expect(instance).to.have.property('transactions');
        // expect(instance.transactions).to.be(expectedValueLiteral);
      });

    });
  });

}));
