/* tslint:disable */
/* eslint-disable */
/**
 * cirquick
 * Backend for Cirquick
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Make all properties in T optional
 * @export
 * @interface PartialResourceInterface_
 */
export interface PartialResourceInterface_ {
    /**
     * 
     * @type {string}
     * @memberof PartialResourceInterface_
     */
    hwSetId?: any;
    /**
     * 
     * @type {string}
     * @memberof PartialResourceInterface_
     */
    hwSetName?: any;
    /**
     * 
     * @type {number}
     * @memberof PartialResourceInterface_
     */
    capacity?: any;
    /**
     * 
     * @type {number}
     * @memberof PartialResourceInterface_
     */
    availablity?: any;
    /**
     * 
     * @type {Array&lt;ResourceInterfaceTransactions&gt;}
     * @memberof PartialResourceInterface_
     */
    transactions?: any;
}
